// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clientes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clientes_default = defineTool({
  name: "list_clientes",
  title: "Listar clientes",
  description: "Lista os clientes (prospects e ativos) do usu\xE1rio autenticado.",
  inputSchema: {
    status: z.enum(["prospect", "active", "inactive"]).optional().describe("Filtra por status do cliente."),
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de clientes a retornar (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sbForUser(ctx).from("clientes").select("id,nome,email,telefone,status,valor_mensal,created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { clientes: data } };
  }
});

// src/lib/mcp/tools/list-projetos.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projetos_default = defineTool2({
  name: "list_projetos",
  title: "Listar projetos",
  description: "Lista os projetos do usu\xE1rio autenticado.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sbForUser2(ctx).from("projetos").select("id,nome,status,prazo,orcamento,cliente_id,created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { projetos: data } };
  }
});

// src/lib/mcp/tools/list-tarefas.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tarefas_default = defineTool3({
  name: "list_tarefas",
  title: "Listar tarefas",
  description: "Lista as tarefas do usu\xE1rio autenticado, opcionalmente filtradas por status.",
  inputSchema: {
    status: z3.enum(["pendente", "em_andamento", "concluida"]).optional(),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sbForUser3(ctx).from("tarefas").select("id,titulo,descricao,status,prioridade,prazo,created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { tarefas: data } };
  }
});

// src/lib/mcp/tools/create-tarefa.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function sbForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_tarefa_default = defineTool4({
  name: "create_tarefa",
  title: "Criar tarefa",
  description: "Cria uma nova tarefa para o usu\xE1rio autenticado.",
  inputSchema: {
    titulo: z4.string().min(1).describe("T\xEDtulo da tarefa."),
    descricao: z4.string().optional(),
    prioridade: z4.enum(["baixa", "media", "alta", "urgente"]).optional(),
    prazo: z4.string().optional().describe("Data limite ISO (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ titulo, descricao, prioridade, prazo }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sbForUser4(ctx).from("tarefas").insert({
      user_id: ctx.getUserId(),
      titulo,
      descricao: descricao ?? null,
      prioridade: prioridade ?? "media",
      prazo: prazo ?? null,
      status: "pendente"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Tarefa criada: ${data.id}` }], structuredContent: { tarefa: data } };
  }
});

// src/lib/mcp/tools/financeiro-resumo.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.23.8";
function sbForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var financeiro_resumo_default = defineTool5({
  name: "financeiro_resumo",
  title: "Resumo financeiro",
  description: "Retorna soma de receitas, despesas e saldo do per\xEDodo informado.",
  inputSchema: {
    inicio: z5.string().optional().describe("Data inicial ISO (YYYY-MM-DD)."),
    fim: z5.string().optional().describe("Data final ISO (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ inicio, fim }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sbForUser5(ctx).from("transacoes").select("tipo,valor,data");
    if (inicio) q = q.gte("data", inicio);
    if (fim) q = q.lte("data", fim);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let receitas = 0, despesas = 0;
    for (const t of data ?? []) {
      const v = Number(t.valor) || 0;
      if (t.tipo === "receita") receitas += v;
      else if (t.tipo === "despesa") despesas += v;
    }
    const resumo = { receitas, despesas, saldo: receitas - despesas, total_transacoes: data?.length ?? 0 };
    return { content: [{ type: "text", text: JSON.stringify(resumo) }], structuredContent: resumo };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hnextembswhejumvxbzd";
var mcp_default = defineMcp({
  name: "hub-empresarial-mcp",
  title: "Hub Empresarial MCP",
  version: "0.1.0",
  instructions: "Ferramentas do Hub Empresarial (Focus Inteligente): gerencie clientes, projetos, tarefas e finan\xE7as da opera\xE7\xE3o do usu\xE1rio autenticado. Toda opera\xE7\xE3o respeita RLS do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clientes_default, list_projetos_default, list_tarefas_default, create_tarefa_default, financeiro_resumo_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
